apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: petclinic-mem-hpa
  labels:
    app: petclinic-app
spec:
  selector:
    app: petclinic-app
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: petclinic-deployment
  metrics:
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 50
